//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormGenerator.Localization.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormGenerator.Localization.Shared.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الالغاء مسبقا.
        /// </summary>
        public static string AlreadyCanceled {
            get {
                return ResourceManager.GetString("AlreadyCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر موجود من قبل.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد قيد افتتاحى.
        /// </summary>
        public static string AlreadyHasEntryWithOpenningBalance {
            get {
                return ResourceManager.GetString("AlreadyHasEntryWithOpenningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا..تم دفع رسوم التقديم مسبقا.
        /// </summary>
        public static string ApplicationFeesAlreadyPaid {
            get {
                return ResourceManager.GetString("ApplicationFeesAlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية الحالية تم تغييرها أثناء العملية.
        /// </summary>
        public static string CurrentQuantityNotMatch {
            get {
                return ResourceManager.GetString("CurrentQuantityNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال رابط استعادة كلمة المرور علي هذا الايميل.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد رسوم دراسية محددة لهذه المرحلة الدراسية.
        /// </summary>
        public static string EnrollmentFeesNotFound {
            get {
                return ResourceManager.GetString("EnrollmentFeesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ من فضلك حاول لاحقاً.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السلة غير صالحة للشراء.
        /// </summary>
        public static string InvalidCartItems {
            get {
                return ResourceManager.GetString("InvalidCartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل تاريخ صحيح.
        /// </summary>
        public static string InValidDates {
            get {
                return ResourceManager.GetString("InValidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد اكثر من وحدة اساسية.
        /// </summary>
        public static string InValidItemStockUnit {
            get {
                return ResourceManager.GetString("InValidItemStockUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في البريد الالكتروني او كلمة المرور.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الخانات اكثر من المطلوب.
        /// </summary>
        public static string MaxDigitValidation {
            get {
                return ResourceManager.GetString("MaxDigitValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحروف اكثر من المطلوب.
        /// </summary>
        public static string MaxLengthValidation {
            get {
                return ResourceManager.GetString("MaxLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحروف اقل من المطلوب.
        /// </summary>
        public static string MinLengthValidation {
            get {
                return ResourceManager.GetString("MinLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الدفع بنجاح.
        /// </summary>
        public static string PaidSuccessfully {
            get {
                return ResourceManager.GetString("PaidSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string RequiredFieldValidation {
            get {
                return ResourceManager.GetString("RequiredFieldValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية المرتجعة أكبر من الكمية المستلمة.
        /// </summary>
        public static string RevertedQuantityBiggerThanReceivedQuantity {
            get {
                return ResourceManager.GetString("RevertedQuantityBiggerThanReceivedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي التحقق من الايميل.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسكين بنجاح.
        /// </summary>
        public static string StudentAssignedSuccessfully {
            get {
                return ResourceManager.GetString("StudentAssignedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاضافة بنجاح.
        /// </summary>
        public static string SuccessfullyCreated {
            get {
                return ResourceManager.GetString("SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You logged out.
        /// </summary>
        public static string SuccessfullyLoggedOut {
            get {
                return ResourceManager.GetString("SuccessfullyLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        public static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجمالى المدفوع أكبر من الرسوم.
        /// </summary>
        public static string TotalPaymentExceedsFees {
            get {
                return ResourceManager.GetString("TotalPaymentExceedsFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المتقدم غير مسجل بقائمة المقبولين.
        /// </summary>
        public static string UnAcceptedApplicant {
            get {
                return ResourceManager.GetString("UnAcceptedApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيد غير متوازن.
        /// </summary>
        public static string UnBalancedEntry {
            get {
                return ResourceManager.GetString("UnBalancedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المتقدم غير مسدد رسوم التقديم.
        /// </summary>
        public static string UnPaidApplicant {
            get {
                return ResourceManager.GetString("UnPaidApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الترتيب بنجاح.
        /// </summary>
        public static string YouSuccessfullyUpdatedDisplayOrder {
            get {
                return ResourceManager.GetString("YouSuccessfullyUpdatedDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الحالة بنجاح.
        /// </summary>
        public static string YouSuccessfullyUpdatedStatus {
            get {
                return ResourceManager.GetString("YouSuccessfullyUpdatedStatus", resourceCulture);
            }
        }
    }
}
